# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MessengerApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MessengerApp

  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Storage'

  target 'MessengerAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MessengerAppUITests' do
    # Pods for testing
  end

end
